---
title: "anh presentation"
format:
  revealjs:
    html-math-method: mathjax
---

## Model Fitting
### Limitation - MNAR

**Process graph (assign uncertain as standard threshold)

## Model Fitting
### Limitation - MNAR

**MNAR graph column on the left side, on the right side is the legend

$X_O$ : Observed variables $\rightarrow$ Tomb, Age, Sex, Overlapping SNPs,...

$X_M$ : Variables that are missing for some observations $\rightarrow$ Kinship status

$R$ : Missingness indicator

## Model Fitting
### Limitation - MNAR

$$
R =
\begin{cases}
1, & \text{if kinship is classified (1st/2nd/3rd)}, \\
0, & \text{if kinship status is classified as "Uncertain".}
\end{cases}
$$

Threshold:

- 1st degree $\rightarrow$ needs $\ge 500 \text{ SNPs}$
- 2nd degree $\rightarrow$ needs $\ge 2000 \text{ SNPs}$
- 3rd degree $\rightarrow$ needs $\ge 15000 \text{ SNPs}$

$$
\Rightarrow R = \mathbb{I}\!\left( \mathrm{OSNP} \ge \text{threshold depending on Kinship status} \right)
$$

$$\Rightarrow P(R | X_O, X_M) \text{ depends on } X_M = \text{Kinship status}$$
$\Rightarrow$ **MNAR**


## Model Fitting
### Limitation - MNAR 
**Solution:** Apply only one threshold 15000 for all degrees of kinship

$$
R =
\begin{cases}
1, & \mathrm{OSNP} \ge 15000, \\
0, & \text{otherwise}
\end{cases}
$$


$$
R = \mathbb{I}\!\left( \mathrm{OSNP} \ge 15000 \right),
$$


$$\Rightarrow P(R | X_O, X_M) \text{ depends on } X_O = \text{Overlapping SNPs}$$

$\Rightarrow$ **MAR**

## Model Fitting
### Model Definition and assumption

**actor partner plot

- Observation: 1 pair (belongs to 2 tombs + 2 individuals)
- Each individual appears in many pairs
- Both within- and across-tomb pairs are observed

$\Rightarrow$ **Multi-Membership Generalized Linear Mixed Model (MM-GLMM)**

## Model Fitting
### Model Definition
Let $Y_{ij} = 1$ if individuals $i$ and $j$ are related, and $Y_{t,ij} = 0$ otherwise.

We assume:

$$
Y_{t,ij} \sim \text{Bernoulli}(\pi_{ij})
$$

where $\pi_{ij} = P(\text{related}_{ij} = 1)$.

**Multi-Membership Generalized Linear Mixed Model (MM-GLMM)**

$$
\text{logit}(\pi_{ij}) = \alpha + \mathbf{X}_{ij}^{\top}\boldsymbol{\beta} 
    + \underbrace{(w_i u_i + w_j u_j)}_{\text{Individual RE}} 
    + \underbrace{(w_{T(i)} v_{T(i)} + w_{T(j)} v_{T(j)})}_{\text{Tomb MM}}
$$


## Model Fitting
### Model Definition
$$
\text{logit}(\pi_{ij}) = \alpha + \mathbf{X}_{ij}^{\top}\boldsymbol{\beta} 
    + \underbrace{(w_i u_i + w_j u_j)}_{\text{Individual RE}} 
    + \underbrace{(w_{T(i)} v_{T(i)} + w_{T(j)} v_{T(j)})}_{\text{Tomb RE}}
$$

Where:

-   $\alpha$: Global intercept
-   $\mathbf{X}_{ij}$: Covariate vector
-   $u_i$: RE for Individual with $u \sim \mathcal{N}(0, \sigma^2_{\text{ind}})$
-   $v_t$: RE for Tomb with $v \sim \mathcal{N}(0, \sigma^2_{\text{tomb}})$
- $w$: Weight  $w_i$ = $w_j$ = $w_{T(i)$ = $w_{T(j)$ = 0.5

## Model Fitting
**DAG to justify predictor choice

## Model Fitting
### Variables

## Model Fitting
### Model Output
separated

## Model Fitting
### Model Output
grouped

## Model Fitting
### Sampling health (Diagnostic)
1. R-hat = 1.00: Excellent, all chains have converged to the same distribution.
2. Effective Sample Size: Pretty large number of independent samples.


## Discussion
### Model Assumption
1. Equal RE weight assumption ($w = 0.5$)

- Theoretically plausible (individual level)
- MM models robust to weight misspecification (Wolff Smith & Beretvas (2014))

## Discussion
### Model Assumption
2. Assumption of RE normality $u, v \sim \mathcal{N}(0, \sigma^2)$

plot_qq_both_effects(imp_binary_separate_nobone)

::: {.columns}

::: {.column width="50%"}

**Individual RE:**

- Right skewed
- **Risk:** Biased intercept and incorrect shape of the estimated RE distribution
- **Mitigation:** Stable fixed effects and variance (McCulloch & Neuhaus (2011))

:::

::: {.column width="50%"}

**Tomb RE:**

- Too few tombs
- **Risk:** Biased RE variance
- **Mitigation:** Unbiased fixed effects (Maas & Hox (2005))
:::

:::

## Discussion
### Model Robust Check
** 2 robust check tables











